kind: pipeline
type: docker
name: docker-demo-drone
steps:
  - name: test
    image: maven:3-jdk-8
    volumes: 
      - name: maven-cache
        path: /root/.m2
      - name: maven-build
        path: /app/build
    commands:
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - mvn test -B
  - name: package
    image: maven:3-jdk-8
    volumes: 
      - name: maven-cache
        path: /root/.m2
      - name: maven-build
        path: /app/build
    commands: 
      - mvn clean package
      - cp target/docker-demo.jar /app/build/docker-demo.jar
      - cp Dockerfile /app/build/Dockerfile
      - cp docker-k8s-demo-deployment.yaml /app/build/docker-k8s-demo-deployment.yaml  # K8S 設定檔
      - cp deploymentservice.yaml /app/build/deploymentservice.yaml # K8S 設定檔
      - cp run.sh /app/build/run.sh
      
  - name: scp files
    image: appleboy/drone-scp
    settings:
      host: 192.168.0.16
      username: root
      password: 
        from_secret: ssh_password_microk8s_vm
      port: 22
      command_timeout: 2m
      target: /mydata/maven/build
      source: ./*
      
  - name: build-start01
    image: appleboy/drone-ssh
    settings:
      host: 172.31.93.122
      username: root
      password:
        from_secret: ssh_password
      port: 2222
      command_timeout: 5m
      script:
        - cd /mydata/maven/build
        - chmod +x run.sh
        - ./run.sh
        
  - name: build-start02
    image: appleboy/drone-ssh
    settings:
      host: 192.168.0.16
      username: vboxuser
      password:
        from_secret: ssh_password_microk8s_vm
      port: 22
      command_timeout: 5m
      script:
        - cd /mydata/maven/build
        - microk8s.kubectl apply -f ./docker-k8s-demo-deployment.yaml

volumes: 
  - name: maven-build
    host:
      path: /mydata/maven/build
  - name: maven-cache
    host:
      path: /mydata/maven/cache
