kind: pipeline
type: docker
name: docker-demo-drone
steps:
  - name: package
    image: maven:3-jdk-8
    volumes: 
      - name: maven-cache
        path: /root/.m2
      - name: maven-build
        path: /app/build
    commands: 
      - mvn clean package
      - cp target/docker-demo.jar /app/build/docker-demo.jar
      - cp Dockerfile /app/build/Dockerfile
      - cp run.sh /app/build/run.sh
  - name: build-start
    image: appleboy/drone-ssh
    settings:
      host: 172.31.93.122
      username: root
      password:
        from_secret: ssh_password # 从Secret中读取SSH密码
      port: 2222
      command_timeout: 5m
      script:
        - cd /mydata/maven/build # 进入宿主机构建目录
        - chmod +x run.sh # 更改为可执行脚本
        - ./run.sh # 运行脚本打包应用镜像并运行
        
volumes: # 定义流水线挂载目录，用于共享数据
  - name: maven-build
    host:
      path: /mydata/maven/build # 从宿主机中挂载的目录
  - name: maven-cache
    host:
      path: /mydata/maven/cache
